version: '3.8'
services:
  nestjsdb:
    container_name: nestjsdb
    image: postgres
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: nestjs
      POSTGRES_PASSWORD: nestjs
      POSTGRES_DB: nestjs
    volumes:
      - ./data/default.sql:/docker-entrypoint-initdb.d/db.sql
      - nestjs-db-data:/var/lib/postgresql/data

  nestjsapp:
    container_name: nestjsapp
    build:
      dockerfile: Dockerfile
      context: "./nestjs"
    ports:
      - 3001:3000  
    depends_on:
      - nestjsdb

  nextjsdb:
    container_name: nextjsdb
    image: postgres
    restart: always
    ports:
      - 54322:5432
    environment:
      POSTGRES_USER: nextjs
      POSTGRES_PASSWORD: nextjs
      POSTGRES_DB: nextjs  
    volumes:
      - ./data/default.sql:/docker-entrypoint-initdb.d/db.sql
      - nextjs-db-data:/var/lib/postgresql/data

volumes:
  nestjs-db-data:
  nextjs-db-data: