import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import './globals.css'
import './styles/normalize.css'
// import './styles/global.sass'
import styles from './styles/main.module.sass'
import { getServerSession } from "next-auth/next"

import Header from "./components/Header/index"
import SessionProvider from './components/SessionProvider'
import PublicLayout from './_layout/publicLayout'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
